services:
  - type: web
    name: mon-app-php  # ← REMPLACER par le nom de votre application
    env: docker
    plan: free  # ou starter, standard, pro selon votre plan
    region: Oregon  # ← REMPLACER par votre région (frankfurt, oregon, singapore, ohio)
    healthCheckPath: /  # ← REMPLACER si vous avez une route spécifique (ex: /health)
    envVars:
      - key: DB_HOST
        value: dpg-d44sitshg0os73fmlf8g-a
      - key: DB_NAME
        value: gpower_bd
      - key: DB_USER
        value: gpower_bd_user
      - key: DB_PASSWORD
        value: 0SXRHezElomtAxHIJKQXogPofa80pwOD
      - key: DB_PORT
        value: "5432"
      - key: DB_SSL
        value: "require"
      - key: APP_URL
        value: https://the-best-gpower-projet.onrender.com
      

      - key: APP_ENV
        value: production